import type { NextComponentType, NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Children, FunctionComponent, ReactNode } from 'react'
import Avatar from '../Elements/Avatar'
import Search from '../Elements/Search'
import ListPriorityElements from '../SideMenu/ListPriorityElements'
import ListSecondaryElements from '../SideMenu/ListSecondaryElements'


const Layout:FunctionComponent<{children:JSX.Element}> = ({children}) => {
  return (
    <div className='grid grid-cols-6 grid-rows-1'>
        <Head>
                <title>HVAC service</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
        </Head>

        <div style={{backgroundColor:'#00508D'}} className='col-start-1'>
            <div className='flex justify-center pt-3'>

                <Image src='/images/LogoMC23.svg' width='80' height='80' quality='100'/>
            </div>
        <ListPriorityElements/>
        <ListSecondaryElements/>
        </div>
        <div className='row-start-1 col-start-2 col-span-5'>
            <div className='flex flex-col'>
            <div className='flex gap-3 pt-3 justify-end row-start-1 h-20 bg-gray-200 border-b-4 border-white shadow-md'>
                <Search/>
                <Avatar/>
                {/* <div className='flex'>
                    <div>Sign in</div>
                    <div>Login</div>
                </div> */}
            </div>
                {children}
            </div>
        </div>
  </div>
  )
}

export default Layout